bvi_cms_list:
    path:     /list
    defaults: { _controller: BviCmsBundle:Cms:index }

bvi_cms_new:
    path:     /new
    defaults: { _controller: BviCmsBundle:Cms:new }
    
bvi_cms_edit:
    path:     /edit/{id}
    defaults: { _controller: BviCmsBundle:Cms:edit }
    
bvi_cms_update_status:
    path:     /update-status
    defaults: { _controller: BviCmsBundle:Cms:updateStatus }    